// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DefaultOutputDirectory(arg1:string):Promise<string>;

export function NativeAlert(arg1:string,arg2:string):Promise<void>;

export function ResizeWindow(arg1:number,arg2:number):Promise<void>;

export function RunFinalCD(arg1:string,arg2:string,arg3:Array<string>):Promise<main.FinalCdResult>;

export function SelectInputFiles():Promise<Array<string>>;

export function SelectOutputDirectory():Promise<string>;
