// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultOutputDirectory(arg1) {
  return window['go']['main']['App']['DefaultOutputDirectory'](arg1);
}

export function NativeAlert(arg1, arg2) {
  return window['go']['main']['App']['NativeAlert'](arg1, arg2);
}

export function ResizeWindow(arg1, arg2) {
  return window['go']['main']['App']['ResizeWindow'](arg1, arg2);
}

export function RunFinalCD(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunFinalCD'](arg1, arg2, arg3);
}

export function SelectInputFiles() {
  return window['go']['main']['App']['SelectInputFiles']();
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}
